export const CONFIG = {
  /** World units across the shorter screen side (the Unity camera's orthographic size 5). */
  shortSide: 10,
  wallThickness: 0.5,
  step: 1 / 60,
  maxFrame: 0.25,
  player: {
    size: 0.5,
    shrinkSize: 0.2,
    growSize: 0.8,
    speed: 7,
    fastSpeed: 12,
    slowSpeed: 2,
    hp: 20,
    invulnTime: 0.6,
  },
  ball: {
    speed: 10,
    seedScale: 0.2,
    growInTime: 1.6,
    growRate: 1 / 30,
    splitInterval: 10,
    splitCount: 3,
    maxBalls: 729,
    demoMaxBalls: 81,
    minSpawnDist: 3,
  },
  pickup: {
    startDelay: 13,
    intervals: [2, 4, 6, 8, 10],
    minBatch: 1,
    maxBatch: 4,
    lifetime: 12,
    blinkTime: 2,
    size: 0.55,
    minPlayerDist: 1,
    edgeMargin: 0.6,
  },
  powerup: {
    duration: 10,
    healthAmount: 5,
    razeKeep: 3,
    fastTime: 2,
    slowTime: 0.5,
  },
  score: {
    start: 1,
    perSplit: 3,
    clearBonus: 25,
  },
  colors: {
    background: '#0063ff',
    wall: '#ffffff',
    player: '#00ff05',
    ball: '#ff0c00',
  },
} as const;
